### ISSUE TITLE
VSCode not finding symbols for tex API

### ISSUE THREAD

**Issue by mtlaurentys** [Josef-Friedrich/vscode_LuaTeX_Lua-API#1]
I have the following extensions installed:
- LaTeX workshop
- Lua
- LuaTeX (this one)

However, when I open a lua file, anywhere I use the `tex` object, I get syntax warnings. When hovering, it reads:
`Undefined global 'tex'. Lua Diagnostics.(undefined-global)`

Here is my `settings.json`:
```
{
    "window.zoomLevel": 3,
    "git.openRepositoryInParentFolders": "never",
    "latex-workshop.latex.recipe.default": "lastUsed",
    "latex-workshop.latex.recipes": [
        {
            "name": "lualatex->biber->lualatex",
            "tools": [
                "lualatex"
            ]
        },
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "lualatex",
            "command": "lualatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "%DOC%"
            ]
        }
    ],
    "luatex.library": ["all", "luatex", "luametatex", "lualatex", "lualibs", "luaotfload"]
}
```
I expected that after adding the `setting.json` libraries it would work right away. I have tried closing and opening, but haven't went far on debugging this, as there are no other installation instructions.

- Are there additional setup steps?
- Are you familiar with the issue, or what info would help debug this?

**Comment by Josef-Friedrich** [comment]
Thank you for reporting this issue. I can't get the addon to run now either ... I can't find out the cause right now. something must have changed.

**Comment by Josef-Friedrich** [comment]
In the meantime you can use the [Addon manager](https://luals.github.io/wiki/addons/#addon-manager) of the [Lua Language Server](https://github.com/LuaLS/lua-language-server). All LuaTeX related libraries are included:

![Addon-Manager](https://github.com/Josef-Friedrich/vscode_LuaTeX_Lua-API/assets/545838/8c02d85a-3e34-4d1e-8165-66ae65e02aa8)

**Comment by Josef-Friedrich** [comment]
Or you clone the libraries

```
git clone https://github.com/Josef-Friedrich/LuaTeX_Lua-API.git <repo>
```

`.vscode/settings.json`:

```json
{
"Lua.workspace.library": [
    "<repo>/library"
  ]
}
```

**Comment by mtlaurentys** [comment]
Hey, sorry for the late follow-up

Both your alternative and your fix worked as expected for me. Thank you for the support!
